---
- name: naontap manage lun
  hosts: localhost
  tasks:
    - name: Create LUN
      na_ontap_lun:
       state: present
       name: ansiblelun
       flexvol_name: ansibleVolume
       vserver: DNAS_NBU 
       size: 5
       size_unit: mb
       space_reserve: True
       hostname: 192.168.100.29 
       username: ansible
       password: Hitachi@123

