---
- name: test
  hosts: localhost
  tasks:
    - name: Create FlexVol
      na_ontap_volume:
       state: present
       name: ansibleVolume
       is_infinite: False
       aggregate_name: LABAFF_1_SSD_1
       size: 20
       size_unit: mb
       junction_path: /ansibleVolume
       vserver: DNAS_NBU
       hostname: 192.168.100.29
       username: ansible
       password: Hitachi@123
